### ISSUE TITLE
pthread.h is missing

### ISSUE THREAD

**Issue by iagoMAO** [10se1ucgo/ace#1]
I've got all of the libs but I still can't build it, CMake's log tells me it can't find the file "pthread.h"
[CMakeError.log](https://github.com/10se1ucgo/ace/files/2178271/CMakeError.log)

**Comment by 10se1ucgo** [comment]
That's weird. I'm not explicitly using pthreads (or threads for that matter) at all. Is there any more to this error log? Also, try updating CMake if possible.
