### ISSUE TITLE
3D coords to build from screen (placing blocks to a x,y,z pos from the screen) [Raymarching? investigating...]

### ISSUE THREAD

**Issue by Edgamer63** [10se1ucgo/ace#10]
Hello, i was wondering how the pos to build a block (No, i dont mean the block building, i mean the block position in x,y,z to build) from screen (yaw and pitch, or whatever how it works with the mouse ever in the center of the screen) works. 

Beforehand, thank you ;D .

**Comment by 10se1ucgo** [comment]
http://www.cse.chalmers.se/edu/year/2010/course/TDA361/grid.pdf

https://github.com/10se1ucgo/ace/blob/master/src/vxl.cpp#L52 is slightly modified from VOXLAP's

**Comment by Edgamer63** [comment]
Thank you my bro :D
