### ISSUE TITLE
Missing Files (MG and RPG)

### ISSUE THREAD

**Issue by Edgamer63** [10se1ucgo/ace#3]
I've seen that here there's no files of such relevant High Weapons:

-MG
-RPG

I rescued some files... so, here it is:

[http://www.mediafire.com/file/8yapeuc9dedjfw8/High%20Weapons.zip](url)

<img src = ""

**Comment by 10se1ucgo** [comment]
Thank you, but I already have these. ace simply just isn't 1.0 (ace.py) ready yet, still working on fixing things up to make development easier before I support 1.0a1/anew

**Comment by Edgamer63** [comment]
uhm, but you have the chopper (helicopter) files? ... if you have it ... can you pass me the files of the propeller and the body of chopper please? : / ... i had all the files a long time ago, but i haved to format my pc. Sad history xDDD,
