### ISSUE TITLE
Various things to fix :D

### ISSUE THREAD

**Issue by Edgamer63** [10se1ucgo/ace#4]
Hello, i've tested the latest release (Alpha 2)... i want to start by congratulate you by your very good work in making more exact sound ambience, and by doing the voxels shading more beatiful in the vertices (Ambient Oclussion). But, i want to make some observations, to perform a gameplay like AoS:

-The "E" key, doesn't copy the voxel colors.
-Missing: 3 Block hitting action with Right-click.
-I think Block draw (when placing a cube) are in a range of 6 or 7 voxels, if not... well, it can look red if the block placing is out of player build-range, it can look very nice :D . 
-The Gui show more than 50 blocks (it's comprehensible if you want to add more blocks when the server implementation will be ready). 

And Also (Very weird):

-The game showed me this Dialog, and boom, suddenly quit the match :c :

<img src = "http://www.mediafire.com/convkey/375c/juanc10u1mwc7d1zg.jpg?size_id=5">

_______________________________________________________________________________________________________________

Well, that's it for this time... i will be testing more... to help you to build-up the Pre 1.0 client.
See you next time my friend :D .

PD: YEAH, YOU ARE DOING THIS WELL! come on comrade :D

**Comment by 10se1ucgo** [comment]
Thanks. I'll be working on these now.
Also, the 3 block action does exist, however there is no animation yet. I'll try to get that done some time.

**Comment by 10se1ucgo** [comment]
Okay, fe6e32c should fix the color copy + block range. I'll try to make a new release some time soon.

**Comment by 10se1ucgo** [comment]
932b742b fixed the fmt crash you screenshotted

**Comment by Edgamer63** [comment]
a little weird bug:

default starting color is:

color_x=4
color_y=1
decimal=2039552
hexadecimal = 1f1f00
normal color= gray


![image](https://user-images.githubusercontent.com/16976638/43362105-9e23a062-92af-11e8-8240-c632fde12780.png)

**Comment by Edgamer63** [comment]
Another one, it just closes the game :/
![image](https://user-images.githubusercontent.com/16976638/43368840-58637a16-9331-11e8-892b-7fd57853a76b.png)

**Comment by 10se1ucgo** [comment]
New release is out now, all of these should be fixed.
