### ISSUE TITLE
[S.O.S] Need Help with map_loading, can you help me? 

### ISSUE THREAD

**Issue by Edgamer63** [10se1ucgo/ace#6]
Hello :D , i need some help. I'm gonna start by telling you why i'm saying this:
https://www.youtube.com/watch?v=VDgR-Dhqwss
>Temporaly enabled view (DISABLED)<

Well, as it shows... i started to doing things like this 3 weeks ago (Yeah, i already do the load and draw kv6 support, and animations for tanks and a lot of more things). Well, this means a lot. Basically, im building very fast... a Whole new game with the community ideas plasmed in. Yeah, i'm doing it. And if it can be better... im working with a language that supports exports to a lot of Operative Systems [Beautiful but hard enough too by doing it alone :/ ].  

Well, i've worked for 2 weeks (a lot AF), in the loading a simple map "bridgewars", and that is where the error   have started. Because, that contains map solids and map spans that in lineal reading, give me a lot of errors, and IDK why....  But i already loaded Gen.vxl (The one that contains only 1 vxl data per 2D coordinates).

The point is that i need some reference, because the sample codes here in: "https://silverspaceship.com/aosmap/aos_file_format.html" , aren't enough. It would be a key move if you can bring me some reference in loading ".vxl" maps. You know, i know... it would be a good thing, and such a spin to the AoS Story. 

PD: The more the secret is keeped, the safer it will be for the B&S Cause.

Thank you, i hope we are friends in the AoS Revitalizator cause.

**Comment by 10se1ucgo** [comment]
Best I can do is point you to https://github.com/10se1ucgo/ace/blob/master/src/vxl.cpp#L56 but the code is mostly directly taken from the link you already gave. It should be relatively straight forward

**Comment by Edgamer63** [comment]
Uhm. and does that load the map without any failure? :/

**Comment by Edgamer63** [comment]
Well, already done! :D , thank you :) . But now, i need a new help... 

Can you help me with debris algorithm? i mean, the floating-structure detector.... It would be good :D (psst, you are already in the Credits of ... well, this game xD)

**Comment by 10se1ucgo** [comment]
The code ace uses is just a slightly modified version of pyspade's. You can find that here https://github.com/10se1ucgo/ace/blob/master/src/world/world.cpp#L98. Whenever a block is destroyed, each of its neighbors are ran through that function (face neighbors, corners are not included). The argument vector is then filled with the positions and colors of each block that was floating.

**Comment by Edgamer63** [comment]
well... where you defined "emplace_back" function? :/ ,  i returned to job in my project :D

**Comment by 10se1ucgo** [comment]
`emplace_back` is a member of `std::vector` since C++11. Alternatively in this case you can use `push_back` if you need an older version for whatever reason.

**Comment by Edgamer63** [comment]
Thanks, it is useful info, i'm converting this to other language ... i still analyze debris algorithm, because i'm recently learning this type of programming xD , Thank you :3 . I think i will ask again anyway :) .

**Comment by Edgamer63** [comment]
Well, i got a question.... And i don't get resolved this correctly, And that's about:

How does the read_map Engine can solve the terrain filling of solid spaces?; Because yes, it can read bytes that get the last upper block (less file size [Cool voxlap :D ]) and if is only one block, it's obviously that the merely rest to down is solid or only water. 

But sometimes you got a span that have only the upper and the bottom blocks, and in the voxlap of AoS, it reads the zone as it is solid. And i dont know, even reading the code of "https://silverspaceship.com/aosmap/aos_file_format.html", i obtain something like:
______________________________________________________________
for(i=z; i < top_color_start; i++)
               setgeom(x,y,i,0);
______________________________________________________________

But it doesn't solve me any question :/ .... I also try with reading for example the vars :+1: 


<blockquote>

Let K = E - S + 1<br>
Let Z = (N-1) - K, or 0 if N=0<br>
Let M = A stored in *next* span, or 64 if the last span of the column
<p>
<table border=1 cellspacing=0 cellpadding=5>
<tr><th>Run</th> <th>Start</th> <th>End</th> <th>Length</th></tr>
<tr><td>air</td> <td>A</td> <td>S-1</td> <td>S-A</td></tr>
<tr><td>top</td> <td>S</td> <td>E</td> <td>E-S+1</td></tr>
<tr><td>solid</td> <td>E+1</td> <td>M-Z-1</td> <td>M-Z - (E+1)</td></tr>
<tr><td>bottom</td> <td>M-Z</td> <td>M-1</td> <td>Z</td></tr>
</table>
</blockquote>



## ![](https://www.mediafire.com/convkey/2b32/e3jxfe1a7rso7bszg.jpg?size_id=5) 

So i come here to keep asking, because i think you may have some clue about it :3 . 

___________________________________________________________________________________________________
PD : 

Also, i recently converted Map of AoS Battle Builder From This:

![image](https://user-images.githubusercontent.com/16976638/50848684-a9977700-1353-11e9-9c5e-6f09f8471b8a.png)

To This : 

![image](https://user-images.githubusercontent.com/16976638/50848750-d0ee4400-1353-11e9-9240-18e90a60b8a7.png)

Also,there's margin :
![image](https://user-images.githubusercontent.com/16976638/50848801-f4b18a00-1353-11e9-8709-26f9eb16accc.png)

So... i think i may add some water to maps that doesn't have it, because in the water spaces, voxlap skips it because of the simple formula of (S = E+1, so, E-S = -1 ; K = (E-S)+1 = 0 ; next_byte = 4*(1+(K)); Skip water if N=0 [TOTALLY CURIOUS NO? xD]) . And i can tell you that i found a way to get the maximum height of a map... it's useful to load AoS Battle Builder Maps :D ... So it means that my version could sup the maps of AoS Battle Builder & maps of Workshop in steam :D , so it will support any maps of any version :O .  So i'm seriously working in it, because i think, that if i work harder, it will be the good part of both worlds :D .

**Comment by Edgamer63** [comment]
Well, i already found a way to do it... and it was tricky xD , now i will do the bitwise operations, for prepare the vertex graphics and see if the World Engine will be working soon(With capacity to load AoS Battle Builder Maps too) :D , so... Thanks :D
