### ISSUE TITLE
Debris Algorithm [SOLVED]

### ISSUE THREAD

**Issue by Edgamer63** [10se1ucgo/ace#9]
Hello! ... i've done A few read... and i start to deglose the Debris Algorithm:

https://github.com/10se1ucgo/ace/blob/master/src/world/world.cpp

But i've found a expression that i don't know where it's from (line 128):

if (ret.second) {
                add_neighboring_nodes(nodes, node.x, node.y, node.z);
            }

What is ret.second?

**Comment by 10se1ucgo** [comment]
unordered_set::emplace returns a pair, the iterator to the inserted object/existing object and a boolean denoting whether or not the item was already in the set (hence the "already visited?")
